server:
  app:
    auto: true
  servlet:
    context-path: /pokemon/v1

spring:
  application:
    name: pokemon

#Spring boot actuator config for health check
endpoints:
  health:
    sensitive: false
    mapping:
      DOWN: SERVICE_UNAVAILABLE

